version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=crud
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres

  db:
    image: postgres
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
